default_platform(:ios)

platform :ios do
  desc "Run tests on the Core framework of SDK"
  lane :test_core do
    pods
    scan(
      workspace: './AblyAssetTracking.xcworkspace',
      scheme: 'Core',
      clean: true,
      code_coverage: true,
    )
  end
end
