import AblyAssetTrackingCore
import AblyAssetTrackingInternal

// This mock was generated by sourcery, however sourcery seems to have problems with generating mocks based on generic
// protocols and it's output doesn't compile without some manual tweaks in the generated code, so all the Worker Queue related
// mocks are not included in the `.sourcery-InternalMocks.yml` file.
public class WorkerQueuePropertiesMock: WorkerQueueProperties {
    public init() {}

    public var isStopped: Bool {
        get { underlyingIsStopped }
        set(value) { underlyingIsStopped = value }
    }
    public var underlyingIsStopped: Bool!
}
