platform :ios, '12.0'

target 'Core' do
  use_frameworks!

  target 'CoreTests' do
  end
end

target 'Publisher' do
  use_frameworks!

  target 'PublisherTests' do
  end
end

target 'Subscriber' do
  use_frameworks!

  target 'SubscriberTests' do
  end
end

target 'PublisherExample' do
  use_frameworks!
end


target 'SubscriberExample' do
  use_frameworks!
end
