platform :ios, '12.0'

def testing_pods
  pod 'Quick', '~> 3.0'
  pod 'Nimble', '~> 9.0'
end

target 'Core' do
  use_frameworks!
  
  target 'CoreTests' do
    testing_pods
  end
end

target 'Publisher' do
  use_frameworks!
  pod 'Ably', '~> 1.2'
  pod 'MapboxCoreNavigation', '~> 1.0'
  
  target 'PublisherTests' do
    testing_pods
  end
end

target 'Subscriber' do
  use_frameworks!
  pod 'Ably', '~> 1.2'
  
  target 'SubscriberTests' do
    testing_pods
  end
end

target 'PublisherExample' do
  use_frameworks!
end


target 'SubscriberExample' do
  use_frameworks!
end
