platform :ios, '12.0'
use_frameworks!

def test_pods
  pod 'Quick', '~> 3.0'
  pod 'Nimble', '~> 9.0'
end

abstract_target 'Common' do
  pod 'Ably', '>= 1.2'
  pod 'MapboxCoreNavigation', '~> 1.0'

  target 'Core' do
  end

  target 'Publisher' do
  end

  target 'Subscriber' do
  end

  target 'PublisherExample' do
  end

  target 'SubscriberExample' do
  end

  target 'SubscriberTests' do
    test_pods
  end

  target 'CoreTests' do
    test_pods
  end

  target 'PublisherTests' do
    test_pods
  end
end
