default_platform(:ios)

platform :ios do
  # Do i have to download dependencies
  
  desc 'Run tests on all targets'
  lane :test do
    xcodebuild(
      scheme: 'ably-asset-tracking-swift-Package',
      configuration: 'Debug',
      sdk: 'iphonesimulator',
      arch: 'x86_64'
    )
  end

  desc 'Run tests on the Core target'
  lane :test_core do
    scan(
      # workspace: './AblyAssetTracking.xcworkspace',
      scheme: 'ably-asset-tracking-swift-Package',
      clean: true,
      code_coverage: true,
    )

    # Clean previous test coverage and generate new one
    sh('rm -rf ./coverage_core')
    slather(
      workspace: './AblyAssetTracking.xcworkspace',
      proj: 'Core/Core.xcodeproj',
      scheme: 'Core',
      output_directory: 'coverage_core',
      html: true,
      ignore: ['Core/Tests/*'],
      source_directory: './Core/Sources'
    )
  end
  
  desc 'Run tests on the Internal target'
  lane :test_internal do
    scan(
      workspace: './AblyAssetTracking.xcworkspace',
      scheme: 'Internal',
      clean: true,
      code_coverage: true,
    )

    # Clean previous test coverage and generate new one
    sh('rm -rf ./coverage_internal')
    slather(
      workspace: './AblyAssetTracking.xcworkspace',
      proj: 'Core/Core.xcodeproj',
      scheme: 'Core',
      output_directory: 'coverage_core',
      html: true,
      ignore: ['Internal/Tests/*'],
      source_directory: './Core/Sources'
    )
  end

  desc 'Run tests on the Publisher target'
  lane :test_publisher do
    scan(
      workspace: './AblyAssetTracking.xcworkspace',
      scheme: 'Publisher',
      clean: true,
      code_coverage: true,
    )

    # Clean previous test coverage and generate new one
    sh('rm -rf ./coverage_publisher')
    slather(
      workspace: './AblyAssetTracking.xcworkspace',
      proj: 'Publisher/Publisher.xcodeproj',
      scheme: 'Publisher',
      output_directory: 'coverage_publisher',
      html: true,
      ignore: ['Core/*', 'Common/*', 'Publisher/Tests/*'],
      source_directory: './Publisher/Sources'
    )
  end

  desc 'Run tests on the Subscriber framework of SDK'
  lane :test_subscriber do
    scan(
      workspace: './AblyAssetTracking.xcworkspace',
      scheme: 'Subscriber',
      clean: true,
      code_coverage: true,
    )
    sh('rm -rf ./coverage_subscriber')
    slather(
      workspace: './AblyAssetTracking.xcworkspace',
      proj: 'Subscriber/Subscriber.xcodeproj',
      scheme: 'Subscriber',
      output_directory: 'coverage_subscriber',
      html: true,
      ignore: ['Core/*', 'Common/*', 'Subscriber/Tests/*'],
      source_directory: './Subscriber/Sources'
    )
  end

  desc 'Build Subscriber SDK and export is as .framework file'
  lane :build_subscriber do
    xcodebuild(
      archive: true,
      # workspace: './AblyAssetTracking.xcworkspace',
      scheme: 'AblyAssetTrackingSubscriber',
      destination: 'generic/platform=iOS',
      archive_path: 'archives/Subscriber.xcarchive',
      xcargs: 'SKIP_INSTALL=NO',
    )
  end

  desc 'Build Publisher SDK and export is as .framework file'
  lane :build_publisher do
    xcodebuild(
      archive: true,
      # workspace: './AblyAssetTracking.xcworkspace',
      scheme: 'AblyAssetTrackingPublisher',
      destination: 'generic/platform=iOS',
      archive_path: 'archives/Publisher.xcarchive',
      xcargs: 'SKIP_INSTALL=NO',
    )
  end

  desc 'Build example apps to validate that there are no build errors'
  lane :build_example_apps do
    xcodebuild(
      workspace: './AblyAssetTracking.xcworkspace',
      scheme: 'PublisherExample',
      configuration: 'Debug',
      sdk: 'iphonesimulator',
      arch: 'x86_64'
    )

    xcodebuild(
      workspace: './AblyAssetTracking.xcworkspace',
      scheme: 'SubscriberExample',
      configuration: 'Debug',
      sdk: 'iphonesimulator',
      arch: 'x86_64'
    )
  end
end
